//
//  ListOrdersViewControllerTests.swift
//  CleanStore
//
//  Created by Raymond Law on 10/31/15.
//  Copyright (c) 2015 Raymond Law. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import XCTest

class ListOrdersViewControllerTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: ListOrdersViewController!
  var window: UIWindow!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    window = UIWindow()
    setupListOrdersViewController()
  }
  
  override func tearDown()
  {
    window = nil
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupListOrdersViewController()
  {
    let bundle = NSBundle(forClass: self.dynamicType)
    let storyboard = UIStoryboard(name: "Main", bundle: bundle)
    sut = storyboard.instantiateViewControllerWithIdentifier("ListOrdersViewController") as! ListOrdersViewController
  }
  
  func loadView()
  {
    window.addSubview(sut.view)
    NSRunLoop.currentRunLoop().runUntilDate(NSDate())
  }
  
  // MARK: Test doubles
  
  class ListOrdersViewControllerOutputSpy: ListOrdersViewControllerOutput
  {
    // MARK: Method call expectations
    var fetchOrdersCalled = false
    
    // MARK: Spied methods
    func fetchOrders(request: ListOrders_FetchOrders_Request)
    {
      fetchOrdersCalled = true
    }
  }
  
  // MARK: Tests
  
  func testShouldFetchOrdersWhenViewIsLoaded()
  {
    // Given
    let listOrdersViewControllerOutputSpy = ListOrdersViewControllerOutputSpy()
    sut.output = listOrdersViewControllerOutputSpy
    
    // When
    loadView()
    
    // Then
    XCTAssert(listOrdersViewControllerOutputSpy.fetchOrdersCalled, "Should fetch orders when the view is loaded")
  }
}
