//
//  ListOrdersPresenter.swift
//  CleanStore
//
//  Created by Raymond Law on 10/31/15.
//  Copyright (c) 2015 Raymond Law. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ListOrdersPresenterInput
{
  func presentSomething(response: ListOrdersResponse)
}

protocol ListOrdersPresenterOutput: class
{
  func displaySomething(viewModel: ListOrdersViewModel)
}

class ListOrdersPresenter: ListOrdersPresenterInput
{
  weak var output: ListOrdersPresenterOutput!
  
  // MARK: Presentation logic
  
  func presentSomething(response: ListOrdersResponse)
  {
    // NOTE: Format the response from the Interactor and pass the result back to the View Controller
    
    let viewModel = ListOrdersViewModel()
    output.displaySomething(viewModel)
  }
}
