//
//  ListOrdersModels.swift
//  CleanStore
//
//  Created by Raymond Law on 10/31/15.
//  Copyright (c) 2015 Raymond Law. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListOrders
{
  // MARK: Use cases
  
  enum FetchOrders
  {
    struct Request
    {
    }
    struct Response
    {
      var orders: [Order]
    }
    struct ViewModel
    {
      typealias DisplayedOrder =
      (
        id: String,
        date: String,
        email: String,
        name: String,
        total: String
      )
      var displayedOrders: [DisplayedOrder]
    }
  }
}
