//
//  ListOrdersInteractor.swift
//  CleanStore
//
//  Created by Raymond Law on 10/31/15.
//  Copyright (c) 2015 Raymond Law. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ListOrdersInteractorInput
{
  func fetchOrders(request: ListOrders_FetchOrders_Request)
}

protocol ListOrdersInteractorOutput
{
}

class ListOrdersInteractor: ListOrdersInteractorInput
{
  var output: ListOrdersInteractorOutput!
  var worker: ListOrdersWorker!
  
  // MARK: Business logic
  
  func fetchOrders(request: ListOrders_FetchOrders_Request)
  {
  }
}
