//
//  CreateOrderRouter.swift
//  CleanStore
//
//  Created by Raymond Law on 8/22/15.
//  Copyright (c) 2015 Raymond Law. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CreateOrderRoutingLogic
{
  func routeToListOrders()
  func routeToShowOrder()
}

protocol CreateOrderDataPassing
{
  var dataStore: CreateOrderDataStore? { get }
}

class CreateOrderRouter: NSObject, RouterProtocol, CreateOrderRoutingLogic, CreateOrderDataPassing
{
  typealias ViewControllerType = CreateOrderViewController
  
  weak var viewController: ViewControllerType?
  var dataStore: CreateOrderDataStore?
  
  // MARK: Routing
  
  func routeToListOrders()
  {
    show(storyboard: .listOrders) { (destinationVC: ListOrdersViewController) in
      var destinationDS = destinationVC.router!.dataStore!
      self.passDataToListOrders(source: self.dataStore!, destination: &destinationDS)
    }
  }
  
  func routeToShowOrder()
  {
    show(storyboard: .showOrder) { (destinationVC: ShowOrderViewController) in
      var destinationDS = destinationVC.router!.dataStore!
      self.passDataToShowOrder(source: self.dataStore!, destination: &destinationDS)
    }
  }
  
  // MARK: Navigation
  
  func navigateToListOrders(source: CreateOrderViewController, destination: ListOrdersViewController)
  {
    source.navigationController?.popViewController(animated: true)
  }
  
  func navigateToShowOrder(source: CreateOrderViewController, destination: ShowOrderViewController)
  {
    source.navigationController?.popViewController(animated: true)
  }
  
  // MARK: Passing data
  
  func passDataToListOrders(source: CreateOrderDataStore, destination: inout ListOrdersDataStore)
  {
  }
  
  func passDataToShowOrder(source: CreateOrderDataStore, destination: inout ShowOrderDataStore)
  {
    destination.order = source.orderToEdit
  }
}

extension CreateOrderRouter {
    
    enum StoryboardIdentifier: String {
        case listOrders = "ListOrders"
        case showOrder = "ShowOrder"
    }
}
