//
//  ShowOrderRouter.swift
//  CleanStore
//
//  Created by Raymond Law on 2/17/16.
//  Copyright (c) 2016 Raymond Law. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates
//  so you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ShowOrderRoutingLogic
{
  func routeToEditOrder()
}

protocol ShowOrderDataPassing
{
  var dataStore: ShowOrderDataStore? { get set }
}

class ShowOrderRouter: RouterProtocol, ShowOrderRoutingLogic, ShowOrderDataPassing
{
  typealias ViewControllerType = ShowOrderViewController
  
  weak var viewController: ViewControllerType?
  var dataStore: ShowOrderDataStore?
  
  // MARK: Routing
  
  func routeToEditOrder()
  {
    show(storyboard: .createOrder) { (destinationVC: CreateOrderViewController) in
      var destinationDS = destinationVC.router!.dataStore!
      self.passDataToEditOrder(source: self.dataStore!, destination: &destinationDS)
    }
  }
  
  // MARK: Navigation
  
  func navigateToEditOrder(source: ShowOrderViewController, destination: CreateOrderViewController)
  {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
  func passDataToEditOrder(source: ShowOrderDataStore, destination: inout CreateOrderDataStore)
  {
    destination.orderToEdit = source.order
  }
}

extension ShowOrderRouter {
    
    enum StoryboardIdentifier: String {
        case createOrder = "CreateOrder"
    }
}
