//
//  ShowOrderInteractor.swift
//  CleanStore
//
//  Created by Raymond Law on 2/17/16.
//  Copyright (c) 2016 Raymond Law. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ShowOrderInteractorInput
{
  func getOrder(request: ShowOrder_GetOrder_Request)
  var order: Order! { get set }
}

protocol ShowOrderInteractorOutput
{
  func presentOrder(response: ShowOrder_GetOrder_Response)
}

class ShowOrderInteractor: ShowOrderInteractorInput
{
  var output: ShowOrderInteractorOutput!
  var worker: ShowOrderWorker!
  
  var order: Order!
  
  // MARK: Business logic
  
  func getOrder(request: ShowOrder_GetOrder_Request)
  {
    let response = ShowOrder_GetOrder_Response(order: order)
    output.presentOrder(response)
  }
}
