//
//  ShowOrderRouter.swift
//  CleanStore
//
//  Created by Raymond Law on 2/12/19.
//  Copyright (c) 2019 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ShowOrderRoutingLogic
{
  func routeToEditOrder(segue: UIStoryboardSegue?)
}

protocol ShowOrderDataPassing
{
  var dataStore: ShowOrderDataStore? { get }
}

class ShowOrderRouter: NSObject, ShowOrderRoutingLogic, ShowOrderDataPassing
{
  weak var viewController: ShowOrderViewController?
  var dataStore: ShowOrderDataStore?
  
  // MARK: Routing
  
  func routeToEditOrder(segue: UIStoryboardSegue?)
  {
    if let segue = segue {
      let destinationVC = segue.destination as! CreateOrderViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToEditOrder(source: dataStore!, destination: &destinationDS)
    } else {
      let destinationVC = viewController?.storyboard?.instantiateViewController(withIdentifier: "CreateOrderViewController") as! CreateOrderViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToEditOrder(source: dataStore!, destination: &destinationDS)
      navigateToEditOrder(source: viewController!, destination: destinationVC)
    }
  }
  
  // MARK: Navigation
  
  func navigateToEditOrder(source: ShowOrderViewController, destination: CreateOrderViewController)
  {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
  func passDataToEditOrder(source: ShowOrderDataStore, destination: inout CreateOrderDataStore)
  {
    destination.orderToEdit = source.order
  }
}
