//
//  ShowOrderConfigurator.swift
//  CleanStore
//
//  Created by Raymond Law on 2/17/16.
//  Copyright (c) 2016 Raymond Law. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension ShowOrderViewController: ShowOrderPresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue)
  }
}

extension ShowOrderInteractor: ShowOrderViewControllerOutput
{
}

extension ShowOrderPresenter: ShowOrderInteractorOutput
{
}

class ShowOrderConfigurator
{
  // MARK: Object lifecycle
  
  static let shared = ShowOrderConfigurator()
  private init() {} //This prevents others from using the default '()' initializer for this class.
  
  // MARK: Configuration
  
  func configure(_ viewController: ShowOrderViewController)
  {
    let router = ShowOrderRouter()
    router.viewController = viewController
    
    let presenter = ShowOrderPresenter()
    presenter.output = viewController
    
    let interactor = ShowOrderInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
