//
//  ShowOrderPresenter.swift
//  CleanStore
//
//  Created by Raymond Law on 2/17/16.
//  Copyright (c) 2016 Raymond Law. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ShowOrderPresenterInput
{
  func presentOrder(_ response: ShowOrder.GetOrder.Response)
}

protocol ShowOrderPresenterOutput: class
{
  func displayOrder(_ viewModel: ShowOrder.GetOrder.ViewModel)
}

class ShowOrderPresenter: ShowOrderPresenterInput
{
  weak var output: ShowOrderPresenterOutput!
  
  let dateFormatter: DateFormatter = {
    let dateFormatter = DateFormatter()
    dateFormatter.dateStyle = .short
    dateFormatter.timeStyle = DateFormatter.Style.none
    return dateFormatter
  }()
  
  let currencyFormatter: NumberFormatter = {
    let currencyFormatter = NumberFormatter()
    currencyFormatter.numberStyle = .currency
    return currencyFormatter
  }()
  
  // MARK: Presentation logic
  
  func presentOrder(_ response: ShowOrder.GetOrder.Response)
  {
    let order = response.order
    
    let date = dateFormatter.string(from: order.date! as Date)
    let total = currencyFormatter.string(from: order.total!)
    let displayedOrder = ShowOrder.GetOrder.ViewModel.DisplayedOrder(id: order.id!, date: date, email: order.email!, name: "\(order.firstName!) \(order.lastName!)", total: total!)
    
    let viewModel = ShowOrder.GetOrder.ViewModel(displayedOrder: displayedOrder)
    output.displayOrder(viewModel)
  }
}
