//
//  ShowOrderInteractorTests.swift
//  CleanStore
//
//  Created by Raymond Law on 2/17/16.
//  Copyright (c) 2016 Raymond Law. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import CleanStore
import XCTest

class ShowOrderInteractorTests: XCTestCase
{
  // MARK: - Subject under test
  
  var sut: ShowOrderInteractor!
  
  // MARK: - Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupShowOrderInteractor()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: - Test setup
  
  func setupShowOrderInteractor()
  {
    sut = ShowOrderInteractor()
  }
  
  // MARK: - Test doubles
  
  class ShowOrderPresentationLogicSpy: ShowOrderPresentationLogic
  {
    // MARK: Method call expectations
    
    var presentOrderCalled = false
    
    // MARK: Spied methods
    
    func presentOrder(response: ShowOrder.GetOrder.Response)
    {
      presentOrderCalled = true
    }
  }
  
  // MARK: - Tests
  
  func testGetOrderShouldAskPresenterToFormatResult()
  {
    // Given
    let showOrderPresentationLogicSpy = ShowOrderPresentationLogicSpy()
    sut.presenter = showOrderPresentationLogicSpy
    sut.order = Seeds.Orders.amy
    
    // When
    let request = ShowOrder.GetOrder.Request()
    sut.getOrder(request: request)
    
    // Then
    XCTAssert(showOrderPresentationLogicSpy.presentOrderCalled, "GetOrder() should ask presenter to format the order")
  }
}
