//
//  ShowOrderPresenterTests.swift
//  CleanStore
//
//  Created by Raymond Law on 2/17/16.
//  Copyright (c) 2016 Raymond Law. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import CleanStore
import XCTest

class ShowOrderPresenterTests: XCTestCase
{
  // MARK: - Subject under test
  
  var sut: ShowOrderPresenter!
  
  // MARK: - Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupShowOrderPresenter()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: - Test setup
  
  func setupShowOrderPresenter()
  {
    sut = ShowOrderPresenter()
  }
  
  // MARK: - Test doubles
  
  class ShowOrderDisplayLogicSpy: ShowOrderDisplayLogic
  {
    // MARK: Method call expectations
    
    var displayOrderCalled = false
    
    // MARK: Argument expectations
    
    var displayOrderViewModel: ShowOrder.GetOrder.ViewModel!
    
    // MARK: Spied methods
    
    func displayOrder(viewModel: ShowOrder.GetOrder.ViewModel)
    {
      displayOrderCalled = true
      displayOrderViewModel = viewModel
    }
  }
  
  // MARK: - Tests
  
  func testPresentOrderShouldFormatOrderForDisplay()
  {
    // Given
    let showOrderDisplayLogicSpy = ShowOrderDisplayLogicSpy()
    sut.viewController = showOrderDisplayLogicSpy
    
    var dateComponents = DateComponents()
    dateComponents.year = 2007
    dateComponents.month = 6
    dateComponents.day = 29
    let date = Calendar.current.date(from: dateComponents)!
    
    var order = Seeds.Orders.amy
    order.date = date
    
    // When
    let response = ShowOrder.GetOrder.Response(order: order)
    sut.presentOrder(response: response)
    
    // Then
    let displayedOrder = showOrderDisplayLogicSpy.displayOrderViewModel.displayedOrder
    XCTAssertEqual(displayedOrder.id, "aaa111", "Presenting order should properly format order ID")
    XCTAssertEqual(displayedOrder.date, "6/29/07", "Presenting order should properly format order date")
    XCTAssertEqual(displayedOrder.email, "amy.apple@clean-swift.com", "Presenting order should properly format email")
    XCTAssertEqual(displayedOrder.name, "Amy Apple", "Presenting order should properly format name")
    XCTAssertEqual(displayedOrder.total, "$1.11", "Presenting order should properly format total")
  }
  
  func testPresentOrderShouldAskViewControllerToDisplayOrder()
  {
    // Given
    let showOrderDisplayLogicSpy = ShowOrderDisplayLogicSpy()
    sut.viewController = showOrderDisplayLogicSpy
    
    // When
    let order = Seeds.Orders.amy
    let response = ShowOrder.GetOrder.Response(order: order)
    sut.presentOrder(response: response)
    
    // Then
    XCTAssert(showOrderDisplayLogicSpy.displayOrderCalled, "Presenting order should ask view controller to display it")
  }
}
